# Generated by Django 4.2.5 on 2023-09-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_alter_hellpdesk_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hellpdesk',
            name='status',
            field=models.CharField(default='new', max_length=250),
        ),
    ]
