# Generated by Django 4.2.5 on 2023-09-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_hellpdesk_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hellpdesk',
            name='actions_taken',
            field=models.TextField(blank=True),
        ),
    ]
