# Generated by Django 4.2.5 on 2023-10-02 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpdesk', '0004_hellpdesk_actions_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='hellpdesk',
            name='asigned_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_problem_more', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hellpdesk',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hellpdesk',
            name='resolved_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_problem_more', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hellpdesk',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('confirmed', 'Confirmed')], default='new', max_length=250),
        ),
    ]
