# Generated by Django 4.2.5 on 2023-10-02 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0006_hellpdesk_creator_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hellpdesk',
            old_name='asigned_user',
            new_name='assigned_user',
        ),
    ]
